name: CI

on:
  push:
    branches:
      - main
      - 'feature/*'
      
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Change directory
        run: cd my-app

      - name: Install dependencies
        run: npm install --prefix my-app

      - name: Run Jest tests
        run: |
              npm test --prefix my-app -- --silent
              echo "Test overview:"
              cat ./my-app/coverage/lcov-report/index.html
            continue-on-error: true
